version: "3.11"

services:
  librarian-database:
    image: postgres:16
    restart: always
    container_name: "librarian-database"
    user: postgres
    volumes:
      - "database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "librarian"
    expose:
      - 5432
    networks:
      - "librarian-network"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5

  librarian-server:
    hostname: "example-librarian-hostname"
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "librarian-postgres"
    ports:
      - 127.0.0.1:21108:21108
    stdin_open: true
    tty: true
    volumes:
      - "database:/volumes/database"
      - type: "bind"
        source: "/tmp/store"
        target: "/tmp/store"
    environment:
      - LIBRARIAN_CONFIG_PATH=server_config.json
      - LIBRARIAN_SERVER_DATABASE_USER=postgres
      - LIBRARIAN_SERVER_DATABASE_PASSWORD=secret
      - LIBRARIAN_BACKGROUND_CONFIG=background_config.json
      - LIBRARIAN_SERVER_DATABASE_DRIVER=sqlite
      - LIBRARIAN_SERVER_DATABASE=/volumes/database/database.db
      - LIBRARIAN_SERVER_PORT=21108
    depends_on:
      librarian-database:
        condition: service_healthy
    networks:
      - "librarian-network"

volumes:
  database:

networks:
  librarian-network:


  
