exclude: "(^docs/server-config.sample.json)|^alembic/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: trailing-whitespace
          exclude: hera_librarian/tests/test_cli.py
        - id: check-added-large-files
        - id: check-ast
        - id: check-json
        - id: check-merge-conflict
        - id: check-xml
        - id: check-yaml
        - id: debug-statements
        - id: end-of-file-fixer
        - id: mixed-line-ending
          args: ['--fix=no']

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear>=23.1.17
          - flake8-builtins
          - flake8-comprehensions
          - flake8-docstrings
          # - flake8-eradicate  # not currently compatible with others
          - flake8-pytest-style
          - flake8-rst-docstrings
          - pep8-naming

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [--skip, "B101", --recursive, pyuvdata]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
