#! /usr/bin/env php
<?php

// copier --task_id id
//
// Start (or restart) a file copy operation.
// This is normally run by copy_master.
//
// task.state tells us how much of the operation we've already done.
// values of task.state:
// 0 initial
// 1 completed rsync
// 2 registered file with remote Librarian
// 3 deleted local copy (if requested)

require_once("hl_db.inc");
require_once("hl_rpc_client.php");

define('DEBUG_COPY', true);

// do the actual file transfer with rsync
//
function do_rsync($task, $local_store, $file) {
    echo "looking up remote store\n";
    $ret = lookup_store($task->remote_site, $task->remote_store);
    if (!$ret->success) {
        echo "couldn't find remote store $task->remote_store: $ret->message\n";
        task_update_error($task->id, $ret->message);
        exit(1);
    }
    $remote_store = $ret->store;
    $dest = $remote_store->rsync_prefix;
    // The '/./' and -R combination here use rsync's "implied directories"
    // feature to put the files into the right subdirectories automatically.
    // This feature was added in version 2.6.7, so if someone is running
    // a too-old version we'll break. In that case we'll probably need to
    // do a "mkdir -p" over SSH to ensure the parent directories exist.
    $path = $local_store->path_prefix.'/./'.$file->name;
    $cmd = "rsync -aR $path $dest 2>&1";
    if ($local_store->ssh_prefix) {
        $cmd = "ssh $local_store->ssh_prefix $cmd";
    }
    if (DEBUG_COPY) {
        echo "copier: execing $cmd\n";
    }
    exec($cmd, $output, $status);
    if ($status) {
        task_update_error($task->id, implode("\n", $output));
        exit(1);
    }
    if (DEBUG_COPY) {
        echo "rsync finished\n";
    }
}

// register file with remote Librarian
//
function do_remote_register($task, $file, $observation) {
    $obs_ret = create_observation(
        $task->remote_site, $file->obs_id, $observation->julian_date,
        $observation->polarization, $observation->length
    );
    $ret = create_file(
        $task->remote_site, $task->remote_store, $file->name, $file->type,
        $file->obs_id, $file->size, $file->md5
    );
    if (!$ret->success) {
        task_update_error($task->id, $ret->message);
        exit(1);
    }
    if (DEBUG_COPY) {
        echo "remote register finished\n";
    }
}

function do_task($task_id) {
    $task = task_lookup_id($task_id);
    if (!$task) {
        die("no such task: $task_id\n");
    }
    $local_store = store_lookup_id($task->local_store_id);
    if (!$local_store) {
        die("no such store: $task->local_store_id\n");
    }
    $file = file_lookup_name_store($task->file_name, $local_store->id);
    if (!$file) {
        die("no such file: $task->file_name");
    }
    $observation = observation_lookup_id($file->obs_id);
    if (!$observation) {
        die("no such obeservation:\n $file->obs_id");
    }
    if ($task->state == 0) {
        do_rsync($task, $local_store, $file);
        $ret = task_update($task->id, "state=1");
        if (!$ret) {
            task_update_error($task->id, "task_update() failed");
            exit(1);
        }
        $task->state = 1;
    }
    if ($task->state < 2) {
        do_remote_register($task, $file, $observation);
        $ret = task_update($task->id, "state=2");
        if (!$ret) {
            task_update_error($task->id, "task_update() failed");
            exit(1);
        }
        $task->state = 2;
    }
    if ($task->delete_when_done) {
        if (file_exists($file->name)) {
	    // This fails if $file is a directory, like a MIRIAD data set.
            $ret = unlink($file->name);
            if (!$ret) {
                task_update_error($task->id, "unlink($file->name) failed");
                exit(1);
            }
        }
        $now = time();
        $ret = file_update($file->id, "deleted=1 and deleted_time=to_timestamp($now)");
        if (!$ret) {
            task_update_error($task->id, "file_update() failed");
            exit(1);
        }
    }

    // all done.  update task record
    //
    $now = time();
    task_update($task->id, "in_progress=0, completed=1, completed_time=to_timestamp($now)");
    if (DEBUG_COPY) {
        echo "task finished\n";
    }
}

$task_id = 0;
for ($i=1; $i<$argc; $i++) {
    switch ($argv[$i]) {
    case '--task_id':
        $task_id = (int)$argv[++$i];
        break;
    default:
        die("copier.php: bad arg: ".$argv[$i]."\n");
    }
}

if (!$task_id) {
    die ("no task ID\n");
}

if (!init_db(get_server_config())) {
    die("can't open DB\n");
}

do_task($task_id);

?>
