version: "3.11"

services:
  librarian-server:
    hostname: "example-librarian-hostname"
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        - LIBRARIAN_CONFIG_PATH=server_config.json
        - LIBRARIAN_SERVER_DATABASE_DRIVER=sqlite
        - LIBRARIAN_SERVER_DATABASE=/volumes/database/database.db
        - LIBRARIAN_SERVER_PORT=21108
    container_name: "librarian"
    ports:
      - 127.0.0.1:21108:21108
    volumes:
      - "database:/volumes/database"
      - "store:/mounts/stores"
    environment:
      - LIBRARIAN_CONFIG_PATH=server_config.json
      - LIBRARIAN_BACKGROUND_CONFIG=background_config.json
      - LIBRARIAN_SERVER_DATABASE_DRIVER=sqlite
      - LIBRARIAN_SERVER_DATABASE=/volumes/database/database.db
      - LIBRARIAN_SERVER_PORT=21108

volumes:
  store: 
  database:
  
