#! /usr/bin/php
<?php
// copy_maker args
// start copy tasks for files that
// - currently have no copy task
// - satisfy the criteria given by args
//
// copy to the given remote site and store
//
// args:
// --filename_like expr
//   filename matches MySQL "like" expr (% is wildcard)
// --type t
//   file type is t
// --remote_site site-name
// --remote_store store-name
//
// This must be run on the Librarian host; it accesses the DB

require_once("hl_db.inc");
require_once("hl_rpc_client.php");

// enumerate files using the given query,
// then arrange to copy them to the given site/store
//
function copy_maker($query, $remote_site, $remote_store) {
    $files = enum_general($query);
    $n = 0;
    foreach ($files as $file) {
        $req = new StdClass;
        $req->task_type = TASK_TYPE_PUSH;
        $req->file_name = $file->name;
        $req->local_store_id = $file->store_id;
        $req->remote_site_name = $remote_site;
        $req->remote_store_name = $remote_store;
        $req->delete_when_done = false;
        if (!task_insert($req)) {
            echo "DB error: ".db_error()."\n";
        } else {
            $n++;
        }
    }
    echo "started $n copies\n";
}
echo "opening server config\n";
$config = get_server_config();
#echo "DB host = ".$config->db_host."\n";
#echo "DB user =".$config->db_user."\n";
#echo "db_passwd =".$config->db_passwd."\n";
#echo "db_name = ".$config->db_name."\n";
#$link=init_db($config);
#echo "DB error = ".db_error($link);
#echo "DB link = ".$link."\n";
if (!init_db(get_server_config())) {
    die("can't open DB\n");
}
echo "[success]\n";
$filename_pattern = null;
$type = null;
$remote_site = null;
$remote_store = null;

for ($i=1; $i<$argc; $i++) {
    if ($argv[$i] == "--filename_like") {
        $filename_pattern = $argv[++$i];
    } else if ($argv[$i] == "--type") {
        $type = $argv[++$i];
    } else if ($argv[$i] == "--remote_site") {
        $remote_site = $argv[++$i];
    } else if ($argv[$i] == "--remote_store") {
        $remote_store = $argv[++$i];
    } else {
        die ("bad arg ".$argv[$i]."\n");
    }
}
if (!$remote_site || !$remote_store) {
    die ("Usage\n");
}

// don't include files that already have active copy tasks
//
$query = "select * from file left join task on file.name = task.file_name where task.id is null";

if ($filename_pattern) {
    $filename_pattern = $link->escape_string($filename_pattern);
    $query .= " and file.name like '$filename_pattern'";
}
if ($type) {
    $type = pg_escape_string($link,$type);
    $query .= " and type='$type'";
}

//echo $query;
copy_maker($query, $remote_site, $remote_store);

?>
