#!/usr/bin/env python
# -*- mode: python; coding: utf-8 -*-
# Copyright 2019 The HERA Collaboration
# Licensed under the 2-clause BSD License
import sys

from hera_librarian.cli import main as _main

def main(*args, **kwargs):
    if not args:
        args = sys.argv

    return _main(*args, **kwargs)

if __name__ == "__main__":
    sys.exit(main())
