name: Formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        continue-on-error: true
        with:
          options: "--check --verbose"
          src: "hera_librarian librarian_background librarian_server librarian_server_scripts alembic tests"
      - uses: isort/isort-action@master
        continue-on-error: true
        with:
          sortPaths: "hera_librarian librarian_background librarian_server librarian_server_scripts alembic tests"