name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                python-version: "3.10"
                cache: "pip"

            - run: pip install -e ".[dev]"

            - run: pytest --cov --cov-report=html --cov-report=xml
