# Copyright 2017 the HERA Collaboration
# Licensed under the 2-clause BSD License.

"""Update observation table

Revision ID: fa863eafacb0
Revises: 464899566429
Create Date: 2023-04-20 17:08:45.941651

"""
import sqlalchemy as sa

from alembic import op

revision = "fa863eafacb0"
down_revision = "464899566429"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation", sa.Column("timestamp_start", sa.DateTime(), nullable=True)
    )
    op.add_column("observation", sa.Column("type", sa.String(length=64), nullable=True))
    op.add_column(
        "observation", sa.Column("observatory", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("telescope", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("stream_ids", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("timestamp_end", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("subtype", sa.String(length=64), nullable=True)
    )
    op.add_column("observation", sa.Column("tags", sa.String(length=64), nullable=True))
    op.add_column(
        "observation", sa.Column("scanification", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("hwp_rate_hz", sa.Float(precision="53"), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("hwp_angles", sa.String(length=64), nullable=True)
    )
    op.add_column("observation", sa.Column("sequencer_ref", sa.Text(), nullable=True))
    op.drop_column("observation", "stop_time_jd")
    op.drop_column("observation", "start_time_jd")
    op.drop_column("observation", "start_lst_hr")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column(
            "start_lst_hr",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "observation",
        sa.Column(
            "start_time_jd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "observation",
        sa.Column(
            "stop_time_jd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("observation", "sequencer_ref")
    op.drop_column("observation", "hwp_angles")
    op.drop_column("observation", "hwp_rate_hz")
    op.drop_column("observation", "scanification")
    op.drop_column("observation", "tags")
    op.drop_column("observation", "subtype")
    op.drop_column("observation", "timestamp_end")
    op.drop_column("observation", "stream_ids")
    op.drop_column("observation", "telescope")
    op.drop_column("observation", "observatory")
    op.drop_column("observation", "type")
    op.drop_column("observation", "timestamp_start")
    # ### end Alembic commands ###
